Pull request
Streaker1425/feature-chatbot pull request #1
Opened 2021-10-12 14:20 UTC by Streaker1425

2021-10-13 20:19 UTC, MaximSomochkin commented on src/nix/education/java/chatbot/chatbot.java
> +public class chatbot {
Наименование классов с Большой буквы

2021-10-13 20:20 UTC, MaximSomochkin commented on src/nix/education/java/chatbot/chatbot.java
> +        String Username = scan.next();
наименование переменных с маленькой буквы

2021-10-13 20:22 UTC, MaximSomochkin commented on src/nix/education/java/chatbot/chatbot.java
> +                System.out.println("Okay, than define the number: "); break;
каждая комманда с новой строки

2021-10-13 20:27 UTC, MaximSomochkin commented on src/nix/education/java/chatbot/chatbot.java
> +                switch(answer) {
Замени switch на if-else

2021-10-18 20:47 UTC, maxsomochkin requested changes

2021-10-18 20:47 UTC, maxsomochkin commented on src/nix/education/java/chatbot/chatbot.java
> +                switch(answer) {
Например:
if(answer.equals("c") || answer.equals("1996")){
System.out.println("You are right!");
points++;
break;
}else{
System.out.println("Try again!");
}
Не совсем понятна проверка на диапазон, если она работает также как и не правильный ответ в диапазоне

2021-10-18 20:47 UTC, maxsomochkin commented on src/nix/education/java/chatbot/chatbot.java
> +                //вывод вариантов ответов
Удали комментарии, название методов и переменных должно пояснять их роль

2021-11-07 23:10 UTC, maxsomochkin approved these changes

2021-11-07 23:10 UTC, maxsomochkin commented on src/nix/education/java/chatbot/Chatbot.java
> +        //начало теста: нужные переменные
Всегда называй переменные и методы так, чтобы не приходилось писать комментарии. Удали их.

2021-11-08 08:32 UTC, merged